// Code generated by protoc-gen-gogo.
// source: v1.proto
// DO NOT EDIT!

/*
	Package winston is a generated protocol buffer package.

	It is generated from these files:
		v1.proto

	It has these top-level messages:
		ReadBucket
		Read
		ReadResponse
		BucketsRequest
		Bucket
		RepoSettings
		WriteRequest
		Row
		EMPTY
*/
package winston

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RepoSettings_Format int32

const (
	RepoSettings_RAW  RepoSettings_Format = 0
	RepoSettings_JSON RepoSettings_Format = 1
)

var RepoSettings_Format_name = map[int32]string{
	0: "RAW",
	1: "JSON",
}
var RepoSettings_Format_value = map[string]int32{
	"RAW":  0,
	"JSON": 1,
}

func (x RepoSettings_Format) String() string {
	return proto.EnumName(RepoSettings_Format_name, int32(x))
}
func (RepoSettings_Format) EnumDescriptor() ([]byte, []int) { return fileDescriptorV1, []int{5, 0} }

type ReadBucket struct {
	Repo        string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	StartTimeMs uint64 `protobuf:"varint,2,opt,name=startTimeMs,proto3" json:"startTimeMs,omitempty"`
	EndTimeMs   uint64 `protobuf:"varint,3,opt,name=endTimeMs,proto3" json:"endTimeMs,omitempty"`
	BucketPath  string `protobuf:"bytes,4,opt,name=bucketPath,proto3" json:"bucketPath,omitempty"`
}

func (m *ReadBucket) Reset()                    { *m = ReadBucket{} }
func (m *ReadBucket) String() string            { return proto.CompactTextString(m) }
func (*ReadBucket) ProtoMessage()               {}
func (*ReadBucket) Descriptor() ([]byte, []int) { return fileDescriptorV1, []int{0} }

type Read struct {
	Repo        string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	StartTimeMs uint64 `protobuf:"varint,2,opt,name=startTimeMs,proto3" json:"startTimeMs,omitempty"`
	EndTimeMs   uint64 `protobuf:"varint,3,opt,name=endTimeMs,proto3" json:"endTimeMs,omitempty"`
}

func (m *Read) Reset()                    { *m = Read{} }
func (m *Read) String() string            { return proto.CompactTextString(m) }
func (*Read) ProtoMessage()               {}
func (*Read) Descriptor() ([]byte, []int) { return fileDescriptorV1, []int{1} }

type ReadResponse struct {
	Repo string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Rows []*Row `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptorV1, []int{2} }

type BucketsRequest struct {
	Repo        string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	StartTimeMs uint64 `protobuf:"varint,2,opt,name=startTimeMs,proto3" json:"startTimeMs,omitempty"`
	EndTimeMs   uint64 `protobuf:"varint,3,opt,name=endTimeMs,proto3" json:"endTimeMs,omitempty"`
}

func (m *BucketsRequest) Reset()                    { *m = BucketsRequest{} }
func (m *BucketsRequest) String() string            { return proto.CompactTextString(m) }
func (*BucketsRequest) ProtoMessage()               {}
func (*BucketsRequest) Descriptor() ([]byte, []int) { return fileDescriptorV1, []int{3} }

type Bucket struct {
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (m *Bucket) Reset()                    { *m = Bucket{} }
func (m *Bucket) String() string            { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()               {}
func (*Bucket) Descriptor() ([]byte, []int) { return fileDescriptorV1, []int{4} }

type RepoSettings struct {
	Repo           string              `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Format         RepoSettings_Format `protobuf:"varint,2,opt,name=format,proto3,enum=winston.RepoSettings_Format" json:"format,omitempty"`
	TimeField      string              `protobuf:"bytes,3,opt,name=timeField,proto3" json:"timeField,omitempty"`
	GroupByFields  []string            `protobuf:"bytes,4,rep,name=groupByFields" json:"groupByFields,omitempty"`
	GroupByBuckets int32               `protobuf:"varint,5,opt,name=groupByBuckets,proto3" json:"groupByBuckets,omitempty"`
}

func (m *RepoSettings) Reset()                    { *m = RepoSettings{} }
func (m *RepoSettings) String() string            { return proto.CompactTextString(m) }
func (*RepoSettings) ProtoMessage()               {}
func (*RepoSettings) Descriptor() ([]byte, []int) { return fileDescriptorV1, []int{5} }

type WriteRequest struct {
	Repo string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	Rows []*Row `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
}

func (m *WriteRequest) Reset()                    { *m = WriteRequest{} }
func (m *WriteRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()               {}
func (*WriteRequest) Descriptor() ([]byte, []int) { return fileDescriptorV1, []int{6} }

type Row struct {
	Data   []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	TimeMs uint64 `protobuf:"varint,3,opt,name=timeMs,proto3" json:"timeMs,omitempty"`
}

func (m *Row) Reset()                    { *m = Row{} }
func (m *Row) String() string            { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()               {}
func (*Row) Descriptor() ([]byte, []int) { return fileDescriptorV1, []int{7} }

type EMPTY struct {
}

func (m *EMPTY) Reset()                    { *m = EMPTY{} }
func (m *EMPTY) String() string            { return proto.CompactTextString(m) }
func (*EMPTY) ProtoMessage()               {}
func (*EMPTY) Descriptor() ([]byte, []int) { return fileDescriptorV1, []int{8} }

func init() {
	proto.RegisterType((*ReadBucket)(nil), "winston.ReadBucket")
	proto.RegisterType((*Read)(nil), "winston.Read")
	proto.RegisterType((*ReadResponse)(nil), "winston.ReadResponse")
	proto.RegisterType((*BucketsRequest)(nil), "winston.BucketsRequest")
	proto.RegisterType((*Bucket)(nil), "winston.Bucket")
	proto.RegisterType((*RepoSettings)(nil), "winston.RepoSettings")
	proto.RegisterType((*WriteRequest)(nil), "winston.WriteRequest")
	proto.RegisterType((*Row)(nil), "winston.Row")
	proto.RegisterType((*EMPTY)(nil), "winston.EMPTY")
	proto.RegisterEnum("winston.RepoSettings_Format", RepoSettings_Format_name, RepoSettings_Format_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for V1 service

type V1Client interface {
	UpsertRepo(ctx context.Context, in *RepoSettings, opts ...grpc.CallOption) (*EMPTY, error)
	Write(ctx context.Context, opts ...grpc.CallOption) (V1_WriteClient, error)
	GetBuckets(ctx context.Context, in *BucketsRequest, opts ...grpc.CallOption) (V1_GetBucketsClient, error)
	ReadBucketByTime(ctx context.Context, in *ReadBucket, opts ...grpc.CallOption) (V1_ReadBucketByTimeClient, error)
	ReadByTime(ctx context.Context, in *Read, opts ...grpc.CallOption) (V1_ReadByTimeClient, error)
}

type v1Client struct {
	cc *grpc.ClientConn
}

func NewV1Client(cc *grpc.ClientConn) V1Client {
	return &v1Client{cc}
}

func (c *v1Client) UpsertRepo(ctx context.Context, in *RepoSettings, opts ...grpc.CallOption) (*EMPTY, error) {
	out := new(EMPTY)
	err := grpc.Invoke(ctx, "/winston.V1/UpsertRepo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v1Client) Write(ctx context.Context, opts ...grpc.CallOption) (V1_WriteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_V1_serviceDesc.Streams[0], c.cc, "/winston.V1/Write", opts...)
	if err != nil {
		return nil, err
	}
	x := &v1WriteClient{stream}
	return x, nil
}

type V1_WriteClient interface {
	Send(*WriteRequest) error
	CloseAndRecv() (*EMPTY, error)
	grpc.ClientStream
}

type v1WriteClient struct {
	grpc.ClientStream
}

func (x *v1WriteClient) Send(m *WriteRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *v1WriteClient) CloseAndRecv() (*EMPTY, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(EMPTY)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *v1Client) GetBuckets(ctx context.Context, in *BucketsRequest, opts ...grpc.CallOption) (V1_GetBucketsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_V1_serviceDesc.Streams[1], c.cc, "/winston.V1/GetBuckets", opts...)
	if err != nil {
		return nil, err
	}
	x := &v1GetBucketsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type V1_GetBucketsClient interface {
	Recv() (*Bucket, error)
	grpc.ClientStream
}

type v1GetBucketsClient struct {
	grpc.ClientStream
}

func (x *v1GetBucketsClient) Recv() (*Bucket, error) {
	m := new(Bucket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *v1Client) ReadBucketByTime(ctx context.Context, in *ReadBucket, opts ...grpc.CallOption) (V1_ReadBucketByTimeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_V1_serviceDesc.Streams[2], c.cc, "/winston.V1/ReadBucketByTime", opts...)
	if err != nil {
		return nil, err
	}
	x := &v1ReadBucketByTimeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type V1_ReadBucketByTimeClient interface {
	Recv() (*ReadResponse, error)
	grpc.ClientStream
}

type v1ReadBucketByTimeClient struct {
	grpc.ClientStream
}

func (x *v1ReadBucketByTimeClient) Recv() (*ReadResponse, error) {
	m := new(ReadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *v1Client) ReadByTime(ctx context.Context, in *Read, opts ...grpc.CallOption) (V1_ReadByTimeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_V1_serviceDesc.Streams[3], c.cc, "/winston.V1/ReadByTime", opts...)
	if err != nil {
		return nil, err
	}
	x := &v1ReadByTimeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type V1_ReadByTimeClient interface {
	Recv() (*ReadResponse, error)
	grpc.ClientStream
}

type v1ReadByTimeClient struct {
	grpc.ClientStream
}

func (x *v1ReadByTimeClient) Recv() (*ReadResponse, error) {
	m := new(ReadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for V1 service

type V1Server interface {
	UpsertRepo(context.Context, *RepoSettings) (*EMPTY, error)
	Write(V1_WriteServer) error
	GetBuckets(*BucketsRequest, V1_GetBucketsServer) error
	ReadBucketByTime(*ReadBucket, V1_ReadBucketByTimeServer) error
	ReadByTime(*Read, V1_ReadByTimeServer) error
}

func RegisterV1Server(s *grpc.Server, srv V1Server) {
	s.RegisterService(&_V1_serviceDesc, srv)
}

func _V1_UpsertRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoSettings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V1Server).UpsertRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/winston.V1/UpsertRepo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V1Server).UpsertRepo(ctx, req.(*RepoSettings))
	}
	return interceptor(ctx, in, info, handler)
}

func _V1_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(V1Server).Write(&v1WriteServer{stream})
}

type V1_WriteServer interface {
	SendAndClose(*EMPTY) error
	Recv() (*WriteRequest, error)
	grpc.ServerStream
}

type v1WriteServer struct {
	grpc.ServerStream
}

func (x *v1WriteServer) SendAndClose(m *EMPTY) error {
	return x.ServerStream.SendMsg(m)
}

func (x *v1WriteServer) Recv() (*WriteRequest, error) {
	m := new(WriteRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _V1_GetBuckets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BucketsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(V1Server).GetBuckets(m, &v1GetBucketsServer{stream})
}

type V1_GetBucketsServer interface {
	Send(*Bucket) error
	grpc.ServerStream
}

type v1GetBucketsServer struct {
	grpc.ServerStream
}

func (x *v1GetBucketsServer) Send(m *Bucket) error {
	return x.ServerStream.SendMsg(m)
}

func _V1_ReadBucketByTime_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadBucket)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(V1Server).ReadBucketByTime(m, &v1ReadBucketByTimeServer{stream})
}

type V1_ReadBucketByTimeServer interface {
	Send(*ReadResponse) error
	grpc.ServerStream
}

type v1ReadBucketByTimeServer struct {
	grpc.ServerStream
}

func (x *v1ReadBucketByTimeServer) Send(m *ReadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _V1_ReadByTime_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Read)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(V1Server).ReadByTime(m, &v1ReadByTimeServer{stream})
}

type V1_ReadByTimeServer interface {
	Send(*ReadResponse) error
	grpc.ServerStream
}

type v1ReadByTimeServer struct {
	grpc.ServerStream
}

func (x *v1ReadByTimeServer) Send(m *ReadResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _V1_serviceDesc = grpc.ServiceDesc{
	ServiceName: "winston.V1",
	HandlerType: (*V1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertRepo",
			Handler:    _V1_UpsertRepo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Write",
			Handler:       _V1_Write_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetBuckets",
			Handler:       _V1_GetBuckets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadBucketByTime",
			Handler:       _V1_ReadBucketByTime_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadByTime",
			Handler:       _V1_ReadByTime_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptorV1,
}

func (m *ReadBucket) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *ReadBucket) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Repo) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintV1(data, i, uint64(len(m.Repo)))
		i += copy(data[i:], m.Repo)
	}
	if m.StartTimeMs != 0 {
		data[i] = 0x10
		i++
		i = encodeVarintV1(data, i, uint64(m.StartTimeMs))
	}
	if m.EndTimeMs != 0 {
		data[i] = 0x18
		i++
		i = encodeVarintV1(data, i, uint64(m.EndTimeMs))
	}
	if len(m.BucketPath) > 0 {
		data[i] = 0x22
		i++
		i = encodeVarintV1(data, i, uint64(len(m.BucketPath)))
		i += copy(data[i:], m.BucketPath)
	}
	return i, nil
}

func (m *Read) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Read) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Repo) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintV1(data, i, uint64(len(m.Repo)))
		i += copy(data[i:], m.Repo)
	}
	if m.StartTimeMs != 0 {
		data[i] = 0x10
		i++
		i = encodeVarintV1(data, i, uint64(m.StartTimeMs))
	}
	if m.EndTimeMs != 0 {
		data[i] = 0x18
		i++
		i = encodeVarintV1(data, i, uint64(m.EndTimeMs))
	}
	return i, nil
}

func (m *ReadResponse) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *ReadResponse) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Repo) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintV1(data, i, uint64(len(m.Repo)))
		i += copy(data[i:], m.Repo)
	}
	if len(m.Rows) > 0 {
		for _, msg := range m.Rows {
			data[i] = 0x12
			i++
			i = encodeVarintV1(data, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *BucketsRequest) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *BucketsRequest) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Repo) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintV1(data, i, uint64(len(m.Repo)))
		i += copy(data[i:], m.Repo)
	}
	if m.StartTimeMs != 0 {
		data[i] = 0x10
		i++
		i = encodeVarintV1(data, i, uint64(m.StartTimeMs))
	}
	if m.EndTimeMs != 0 {
		data[i] = 0x18
		i++
		i = encodeVarintV1(data, i, uint64(m.EndTimeMs))
	}
	return i, nil
}

func (m *Bucket) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Bucket) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Path) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintV1(data, i, uint64(len(m.Path)))
		i += copy(data[i:], m.Path)
	}
	return i, nil
}

func (m *RepoSettings) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *RepoSettings) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Repo) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintV1(data, i, uint64(len(m.Repo)))
		i += copy(data[i:], m.Repo)
	}
	if m.Format != 0 {
		data[i] = 0x10
		i++
		i = encodeVarintV1(data, i, uint64(m.Format))
	}
	if len(m.TimeField) > 0 {
		data[i] = 0x1a
		i++
		i = encodeVarintV1(data, i, uint64(len(m.TimeField)))
		i += copy(data[i:], m.TimeField)
	}
	if len(m.GroupByFields) > 0 {
		for _, s := range m.GroupByFields {
			data[i] = 0x22
			i++
			l = len(s)
			for l >= 1<<7 {
				data[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			data[i] = uint8(l)
			i++
			i += copy(data[i:], s)
		}
	}
	if m.GroupByBuckets != 0 {
		data[i] = 0x28
		i++
		i = encodeVarintV1(data, i, uint64(m.GroupByBuckets))
	}
	return i, nil
}

func (m *WriteRequest) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *WriteRequest) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Repo) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintV1(data, i, uint64(len(m.Repo)))
		i += copy(data[i:], m.Repo)
	}
	if len(m.Rows) > 0 {
		for _, msg := range m.Rows {
			data[i] = 0x12
			i++
			i = encodeVarintV1(data, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(data[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *Row) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *Row) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintV1(data, i, uint64(len(m.Data)))
		i += copy(data[i:], m.Data)
	}
	if m.TimeMs != 0 {
		data[i] = 0x18
		i++
		i = encodeVarintV1(data, i, uint64(m.TimeMs))
	}
	return i, nil
}

func (m *EMPTY) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *EMPTY) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func encodeFixed64V1(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32V1(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintV1(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *ReadBucket) Size() (n int) {
	var l int
	_ = l
	l = len(m.Repo)
	if l > 0 {
		n += 1 + l + sovV1(uint64(l))
	}
	if m.StartTimeMs != 0 {
		n += 1 + sovV1(uint64(m.StartTimeMs))
	}
	if m.EndTimeMs != 0 {
		n += 1 + sovV1(uint64(m.EndTimeMs))
	}
	l = len(m.BucketPath)
	if l > 0 {
		n += 1 + l + sovV1(uint64(l))
	}
	return n
}

func (m *Read) Size() (n int) {
	var l int
	_ = l
	l = len(m.Repo)
	if l > 0 {
		n += 1 + l + sovV1(uint64(l))
	}
	if m.StartTimeMs != 0 {
		n += 1 + sovV1(uint64(m.StartTimeMs))
	}
	if m.EndTimeMs != 0 {
		n += 1 + sovV1(uint64(m.EndTimeMs))
	}
	return n
}

func (m *ReadResponse) Size() (n int) {
	var l int
	_ = l
	l = len(m.Repo)
	if l > 0 {
		n += 1 + l + sovV1(uint64(l))
	}
	if len(m.Rows) > 0 {
		for _, e := range m.Rows {
			l = e.Size()
			n += 1 + l + sovV1(uint64(l))
		}
	}
	return n
}

func (m *BucketsRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.Repo)
	if l > 0 {
		n += 1 + l + sovV1(uint64(l))
	}
	if m.StartTimeMs != 0 {
		n += 1 + sovV1(uint64(m.StartTimeMs))
	}
	if m.EndTimeMs != 0 {
		n += 1 + sovV1(uint64(m.EndTimeMs))
	}
	return n
}

func (m *Bucket) Size() (n int) {
	var l int
	_ = l
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovV1(uint64(l))
	}
	return n
}

func (m *RepoSettings) Size() (n int) {
	var l int
	_ = l
	l = len(m.Repo)
	if l > 0 {
		n += 1 + l + sovV1(uint64(l))
	}
	if m.Format != 0 {
		n += 1 + sovV1(uint64(m.Format))
	}
	l = len(m.TimeField)
	if l > 0 {
		n += 1 + l + sovV1(uint64(l))
	}
	if len(m.GroupByFields) > 0 {
		for _, s := range m.GroupByFields {
			l = len(s)
			n += 1 + l + sovV1(uint64(l))
		}
	}
	if m.GroupByBuckets != 0 {
		n += 1 + sovV1(uint64(m.GroupByBuckets))
	}
	return n
}

func (m *WriteRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.Repo)
	if l > 0 {
		n += 1 + l + sovV1(uint64(l))
	}
	if len(m.Rows) > 0 {
		for _, e := range m.Rows {
			l = e.Size()
			n += 1 + l + sovV1(uint64(l))
		}
	}
	return n
}

func (m *Row) Size() (n int) {
	var l int
	_ = l
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovV1(uint64(l))
	}
	if m.TimeMs != 0 {
		n += 1 + sovV1(uint64(m.TimeMs))
	}
	return n
}

func (m *EMPTY) Size() (n int) {
	var l int
	_ = l
	return n
}

func sovV1(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozV1(x uint64) (n int) {
	return sovV1(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ReadBucket) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowV1
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReadBucket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReadBucket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Repo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthV1
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Repo = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTimeMs", wireType)
			}
			m.StartTimeMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.StartTimeMs |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTimeMs", wireType)
			}
			m.EndTimeMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.EndTimeMs |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BucketPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthV1
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BucketPath = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipV1(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthV1
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Read) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowV1
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Read: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Read: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Repo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthV1
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Repo = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTimeMs", wireType)
			}
			m.StartTimeMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.StartTimeMs |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTimeMs", wireType)
			}
			m.EndTimeMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.EndTimeMs |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipV1(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthV1
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReadResponse) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowV1
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReadResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReadResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Repo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthV1
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Repo = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rows", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthV1
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rows = append(m.Rows, &Row{})
			if err := m.Rows[len(m.Rows)-1].Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipV1(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthV1
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BucketsRequest) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowV1
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BucketsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BucketsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Repo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthV1
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Repo = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTimeMs", wireType)
			}
			m.StartTimeMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.StartTimeMs |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTimeMs", wireType)
			}
			m.EndTimeMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.EndTimeMs |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipV1(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthV1
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Bucket) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowV1
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Bucket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Bucket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthV1
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipV1(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthV1
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RepoSettings) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowV1
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RepoSettings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RepoSettings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Repo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthV1
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Repo = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Format", wireType)
			}
			m.Format = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.Format |= (RepoSettings_Format(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeField", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthV1
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimeField = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupByFields", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthV1
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GroupByFields = append(m.GroupByFields, string(data[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupByBuckets", wireType)
			}
			m.GroupByBuckets = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.GroupByBuckets |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipV1(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthV1
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WriteRequest) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowV1
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WriteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WriteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Repo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthV1
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Repo = string(data[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rows", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthV1
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rows = append(m.Rows, &Row{})
			if err := m.Rows[len(m.Rows)-1].Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipV1(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthV1
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Row) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowV1
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Row: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Row: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthV1
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], data[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeMs", wireType)
			}
			m.TimeMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowV1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				m.TimeMs |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipV1(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthV1
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EMPTY) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowV1
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EMPTY: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EMPTY: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipV1(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthV1
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipV1(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowV1
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowV1
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowV1
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthV1
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowV1
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipV1(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthV1 = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowV1   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("v1.proto", fileDescriptorV1) }

var fileDescriptorV1 = []byte{
	// 520 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xf6, 0xd6, 0x8e, 0xd3, 0x4c, 0xd3, 0x10, 0x2d, 0x14, 0xac, 0x10, 0x59, 0xd6, 0x0a, 0x21,
	0x5f, 0x70, 0x49, 0xf8, 0x39, 0x70, 0xc3, 0x82, 0x22, 0x21, 0x15, 0xaa, 0x6d, 0xa1, 0x82, 0x9b,
	0x53, 0x6f, 0x5d, 0x0b, 0xe2, 0x35, 0xde, 0x35, 0x51, 0x6f, 0x3c, 0x06, 0x6f, 0xc0, 0xab, 0xf4,
	0xc8, 0x23, 0xd0, 0xf0, 0x22, 0x68, 0x37, 0x6e, 0xed, 0x94, 0x52, 0x4e, 0xbd, 0xcd, 0x7c, 0x33,
	0xdf, 0xcc, 0xb7, 0xdf, 0x7a, 0x0d, 0xab, 0x5f, 0x47, 0x41, 0x5e, 0x70, 0xc9, 0x71, 0x7b, 0x96,
	0x66, 0x42, 0xf2, 0x6c, 0xf0, 0x20, 0x49, 0xe5, 0x51, 0x39, 0x09, 0x0e, 0xf8, 0x74, 0x33, 0xe1,
	0x09, 0xdf, 0xd4, 0xf5, 0x49, 0x79, 0xa8, 0x33, 0x9d, 0xe8, 0x68, 0xc1, 0x23, 0xdf, 0x10, 0x00,
	0x65, 0x51, 0x1c, 0x96, 0x07, 0x9f, 0x98, 0xc4, 0x18, 0xac, 0x82, 0xe5, 0xdc, 0x41, 0x1e, 0xf2,
	0x3b, 0x54, 0xc7, 0xd8, 0x83, 0x35, 0x21, 0xa3, 0x42, 0xee, 0xa5, 0x53, 0xb6, 0x2d, 0x9c, 0x15,
	0x0f, 0xf9, 0x16, 0x6d, 0x42, 0x78, 0x08, 0x1d, 0x96, 0xc5, 0x55, 0xdd, 0xd4, 0xf5, 0x1a, 0xc0,
	0x2e, 0xc0, 0x44, 0x4f, 0xdf, 0x89, 0xe4, 0x91, 0x63, 0xe9, 0xc9, 0x0d, 0x84, 0x7c, 0x04, 0x4b,
	0x29, 0xb8, 0x8e, 0xdd, 0xe4, 0x05, 0x74, 0xd5, 0x6c, 0xca, 0x44, 0xce, 0x33, 0xc1, 0xfe, 0xb1,
	0xc3, 0x2a, 0xf8, 0x4c, 0x0d, 0x37, 0xfd, 0xb5, 0x71, 0x37, 0xa8, 0x9c, 0x0c, 0x28, 0x9f, 0x51,
	0x5d, 0x21, 0x31, 0xf4, 0x16, 0xfe, 0x08, 0xca, 0xbe, 0x94, 0x4c, 0x5c, 0x8b, 0x4f, 0x64, 0x08,
	0x76, 0x7d, 0x0b, 0xb9, 0xf2, 0xaa, 0x9a, 0xae, 0x62, 0x72, 0x8a, 0xd4, 0x51, 0x72, 0xbe, 0xcb,
	0xa4, 0x4c, 0xb3, 0x44, 0x5c, 0x2a, 0xe1, 0x31, 0xd8, 0x87, 0xbc, 0x98, 0x46, 0x52, 0x6f, 0xef,
	0x8d, 0x87, 0xf5, 0x61, 0x1a, 0xd4, 0x60, 0x4b, 0xf7, 0xd0, 0xaa, 0x57, 0xc9, 0x92, 0xe9, 0x94,
	0x6d, 0xa5, 0xec, 0x73, 0xac, 0x65, 0x75, 0x68, 0x0d, 0xe0, 0x7b, 0xb0, 0x9e, 0x14, 0xbc, 0xcc,
	0xc3, 0x63, 0x9d, 0x0b, 0xc7, 0xf2, 0x4c, 0xbf, 0x43, 0x97, 0x41, 0x7c, 0x1f, 0x7a, 0x15, 0x50,
	0x39, 0xe5, 0xb4, 0x3c, 0xe4, 0xb7, 0xe8, 0x05, 0x94, 0xdc, 0x05, 0x7b, 0xb1, 0x1d, 0xb7, 0xc1,
	0xa4, 0xcf, 0xf7, 0xfb, 0x06, 0x5e, 0x05, 0xeb, 0xf5, 0xee, 0xdb, 0x37, 0x7d, 0xa4, 0x6e, 0x6b,
	0xbf, 0x48, 0x25, 0xbb, 0xda, 0xe5, 0xff, 0xdd, 0xd6, 0x08, 0x4c, 0xca, 0x67, 0x8a, 0x1c, 0x47,
	0x32, 0xd2, 0x4e, 0x74, 0xa9, 0x8e, 0xf1, 0x6d, 0xb0, 0x65, 0xd3, 0xfd, 0x2a, 0x23, 0x6d, 0x68,
	0xbd, 0xdc, 0xde, 0xd9, 0xfb, 0x30, 0xfe, 0xb1, 0x02, 0x2b, 0xef, 0x47, 0xf8, 0x09, 0xc0, 0xbb,
	0x5c, 0xb0, 0x42, 0x2a, 0xdb, 0xf0, 0xc6, 0xa5, 0x2e, 0x0e, 0x7a, 0xe7, 0xb0, 0xe6, 0x12, 0x03,
	0x8f, 0xa1, 0xa5, 0xf5, 0x37, 0x18, 0xcd, 0xf3, 0xfc, 0xcd, 0xf0, 0x11, 0x7e, 0x06, 0xf0, 0x8a,
	0xc9, 0xca, 0x1e, 0x7c, 0xe7, 0xbc, 0x63, 0xf9, 0x83, 0x1b, 0xdc, 0xb8, 0x50, 0x20, 0xc6, 0x43,
	0x84, 0x43, 0xe8, 0xd7, 0x6f, 0x37, 0x3c, 0x56, 0xdf, 0x11, 0xbe, 0xd9, 0x10, 0x7b, 0x56, 0x1a,
	0x6c, 0x2c, 0x81, 0x67, 0xaf, 0x41, 0xcf, 0x78, 0x5a, 0xbd, 0xff, 0x05, 0x7b, 0x7d, 0xa9, 0xf1,
	0x0a, 0x5e, 0x78, 0xeb, 0xe4, 0xd4, 0x35, 0x4e, 0xe6, 0x2e, 0xfa, 0x39, 0x77, 0xd1, 0xaf, 0xb9,
	0x8b, 0xbe, 0xff, 0x76, 0x8d, 0x89, 0xad, 0xff, 0x2a, 0x8f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xb9, 0xfc, 0xb6, 0x4a, 0x99, 0x04, 0x00, 0x00,
}
